### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by bilelmoussaoui** [andrewSC/checkthat#15]
Hey,
I have just found this repository while reading the Archlinux mailing list (congrats on being accepted as a trusted user).

Whenever i run the application I get this error:
```shell
Traceback (most recent call last):
  File "/usr/bin/checkthat", line 11, in <module>
    load_entry_point('Checkthat==1.0', 'console_scripts', 'checkthat')()
  File "/usr/lib/python3.6/site-packages/checkthat/checkthat.py", line 45, in main
    config = read_config(config_path)
  File "/usr/lib/python3.6/site-packages/checkthat/checkthat.py", line 35, in read_config
    with open(conf_path, 'r') as conf_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.6/site-packages/config.toml'
```
I have modified the `checkthat.py` file and added a print to get the exact value of the `conf_path` which is `/usr/lib/python3.6/site-packages/config.toml`

As the config.toml is used to configure the checkthat way of working (as far as i know). The file should be placed somewhere else; like in /usr/share?
And provide the possibility for the user to modify that file; by reading this file `$HOME/.config/checkthat.toml` first and falling back to the preconfigured file?

**Comment by andrewSC** [comment]
Wow, super sorry for not seeing this sooner... I apparently wasn't watching the repo (I thought GH auto watched repos owners created?) so I wasn't aware comments had been made... Thanks for the kind words :)

I believe you're right, I honestly need to revisit how this is installed...
